name: 'Terraform Plan'
on: 
  push:
    paths: 
    - "declarations/terraform/**"
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        
      - name: get list of changed files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
 #       with:
 #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: set terraform option
        run:  terraform 0.12upgrade
      
      - name: 'Terraform Init'
        run: terraform init ./declarations/terraform

 #     - name: 'Terraform Format'
 #       run: terraform fmt -check ./declarations/terraform

      - name: 'Terraform Plan'
        run: terraform plan -var 'password=${{ secrets.bigip_aws_password }}' -var 'filelist=${{ steps.files.output.all }}' ./declarations/terraform 

      - name: 'Terraform Apply'
        run: terraform apply -var 'password=${{ secrets.bigip_aws_password }}' -var 'filelist=${{ steps.files.output.all }}' --auto-approve ./declarations/terraform 


        
